apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influx 
    spec:
      containers:
      - name: influx
        image: influxdb:1.7.8
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
