apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: sample
data:
  elasticsearch.yml: |
    cluster.name: my-elastic-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    discovery.type: "single-node"
  ES_JAVA_OPTS: -Xms512m -Xmx1024m
