apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-loadbalancer
spec:
  selector:
    app: es-cluster
  ports:
  - name: http #Used for external commands
    port: 9200
    targetPort: 9200
  - name: transport #Not used in this configuration
    port: 9300
    targetPort: 9300
