apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  replicas: 3 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld
      name: helloworld
    spec:
      containers:
      - name: helloworld
        image: nginx 
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: nginxconf
          mountPath: /etc/nginx
        - name: indexhtml
          mountPath: /www/data
      volumes:
        - name: nginxconf
          configMap:
            name: helloworldconf
        - name: indexhtml
          configMap:
            name: helloworldhtml
