apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: sample 
spec:
  selector:
    matchLabels:
        app: helloworld
  replicas: 3 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld
      name: helloworld
    spec:
      containers:
      - name: telegraf
        image: telegraf
        imagePullPolicy: Always
        volumeMounts:
        - name: telegrafconf
          mountPath: /etc/telegraf
      - name: helloworld
        image: nginx 
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: nginxconf
          mountPath: /etc/nginx
        - name: indexhtml
          mountPath: /www/data
      volumes:
        - name: nginxconf
          configMap:
            name: helloworldconf
        - name: indexhtml
          configMap:
            name: helloworldhtml
        - name: telegrafconf
          configMap:
            name: telegrafnginx
