apiVersion: apps/v1 
kind: Deployment
metadata:
  name: influx
  namespace: sample
spec:
  selector:
    matchLabels:
      app: influx
  replicas: 1
  template:
    metadata:
      labels:
        app: influx 
    spec:
      containers:
      - name: influx
        image: influxdb:1.7.8
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
