---
- hosts: all
  tasks:
  
        - name: switch to legacy iptables
          shell: "update-alternatives --set iptables /usr/sbin/iptables-legacy"               

        - name: install yum utils
          yum:
                  name: 
                          - yum-utils
                          - device-mapper-persistent-data
                          - lvm2
                  state: present

        - name: add docker repo
          shell: "dnf config-manager --add-repo  https://download.docker.com/linux/centos/docker-ce.repo"

        - name: update yum cache
          yum:
                  update_cache: yes

        - name: install docker
          yum:
                  name: docker-ce-18.06.2.ce
                  state: present

        - name: create docker dir
          file:
                  path: /etc/docker
                  state: directory

        - name: copy daemon config
          copy:
                  src: daemon.json
                  dest: /etc/docker/daemon.json

        - name: make systemd docker dir
          file:
                  path: /etc/systemd/system/docker.service.d
                  state: directory

        - name: Add kubernetes repo
          copy:
                  src: kubernetes.repo
                  dest: /etc/yum.repos.d/kubernetes.repo

        - name: update selinux
          shell: "setenforce 0 && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config"

        - name: install kube
          yum:
                  name:
                          - kubelet
                          - kubeadm
                          - kubectl
                  disable_excludes: kubernetes
                  state: present

        - name: start and enable docker
          systemd:
                 name: docker
                 state: started
                 enabled: yes


        - name: enable kubelet
          systemd:
                 name: kubelet
                 state: started
                 enabled: yes

        - name: update /etc/hosts with master IP manual assignment
          template:
                  src: hosts.j2
                  dest: /etc/hosts
                  owner: root
                  group: root

        - name: allow firewalld 6443
          firewalld:
                  port: 6443/tcp
                  permanent: yes
                  state: enabled

        - name: allow firewalld 10250
          firewalld:
                  port: 10250/tcp
                  permanent: yes
                  state: enabled

        - name: disable swap
          shell: "swapoff -a"
